---
- name: Gather facts from devices
  hosts: nxosn9k
  gather_facts: yes
  tasks:
    - name: Gather device facts
      ansible.builtin.setup:
      register: gathered_facts

    # - name: Display gathered facts on the screen
    #   debug:
    #     var: ansible_facts

    - name: Save facts to a file
      ansible.builtin.copy:
        content: "{{ gathered_facts | to_nice_json }}"
        dest: ./{{ inventory_hostname }}_facts_output.json  
