---
- name: Name packages using a loop
  hosts: linuxminthosts
  gather_facts: false
  become: no
  tasks:
    - name: Create a file
      shell: echo 'Begin file' > /home/zolcs/Desktop/loops.txt
    - name: install packages
    # Just as for items in item in python:
      shell: echo "{{item}}" >> /home/zolcs/Desktop/loops.txt
      with_items:
        - vim
        - nano
        - python
